INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302672, 'AD', 'Andorra', 'EU', 'https://en.wikipedia.org/wiki/Andorra', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302618, 'AE', 'United Arab Emirates', 'AS', 'https://en.wikipedia.org/wiki/United_Arab_Emirates', 'UAE,مطارات في الإمارات العربية المتحدة');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302619, 'AF', 'Afghanistan', 'AS', 'https://en.wikipedia.org/wiki/Afghanistan', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302722, 'AG', 'Antigua and Barbuda', NULL, 'https://en.wikipedia.org/wiki/Antigua_and_Barbuda', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302723, 'AI', 'Anguilla', NULL, 'https://en.wikipedia.org/wiki/Anguilla', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302673, 'AL', 'Albania', 'EU', 'https://en.wikipedia.org/wiki/Albania', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302620, 'AM', 'Armenia', 'AS', 'https://en.wikipedia.org/wiki/Armenia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302556, 'AO', 'Angola', 'AF', 'https://en.wikipedia.org/wiki/Angola', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302615, 'AQ', 'Antarctica', 'AN', 'https://en.wikipedia.org/wiki/Antarctica', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302789, 'AR', 'Argentina', 'SA', 'https://en.wikipedia.org/wiki/Argentina', 'Aeropuertos de Argentina');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302763, 'AS', 'American Samoa', 'OC', 'https://en.wikipedia.org/wiki/American_Samoa', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302674, 'AT', 'Austria', 'EU', 'https://en.wikipedia.org/wiki/Austria', 'Flughäfen in Österreich');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302764, 'AU', 'Australia', 'OC', 'https://en.wikipedia.org/wiki/Australia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302725, 'AW', 'Aruba', NULL, 'https://en.wikipedia.org/wiki/Aruba', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302621, 'AZ', 'Azerbaijan', 'AS', 'https://en.wikipedia.org/wiki/Azerbaijan', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302675, 'BA', 'Bosnia and Herzegovina', 'EU', 'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302726, 'BB', 'Barbados', NULL, 'https://en.wikipedia.org/wiki/Barbados', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302622, 'BD', 'Bangladesh', 'AS', 'https://en.wikipedia.org/wiki/Bangladesh', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302676, 'BE', 'Belgium', 'EU', 'https://en.wikipedia.org/wiki/Belgium', 'Aéroports de Belgique,Luchthavens van België');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302557, 'BF', 'Burkina Faso', 'AF', 'https://en.wikipedia.org/wiki/Burkina_Faso', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302677, 'BG', 'Bulgaria', 'EU', 'https://en.wikipedia.org/wiki/Bulgaria', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302623, 'BH', 'Bahrain', 'AS', 'https://en.wikipedia.org/wiki/Bahrain', 'مطارات البحرين');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302558, 'BI', 'Burundi', 'AF', 'https://en.wikipedia.org/wiki/Burundi', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302559, 'BJ', 'Benin', 'AF', 'https://en.wikipedia.org/wiki/Benin', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302760, 'BL', 'Saint Barthélemy', NULL, 'https://en.wikipedia.org/wiki/Saint_Barthélemy', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302727, 'BM', 'Bermuda', NULL, 'https://en.wikipedia.org/wiki/Bermuda', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302624, 'BN', 'Brunei', 'AS', 'https://en.wikipedia.org/wiki/Brunei', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302790, 'BO', 'Bolivia', 'SA', 'https://en.wikipedia.org/wiki/Bolivia', 'Aeropuertos de Bolivia');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302724, 'BQ', 'Caribbean Netherlands', NULL, 'https://en.wikipedia.org/wiki/Caribbean_Netherlands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302791, 'BR', 'Brazil', 'SA', 'https://en.wikipedia.org/wiki/Brazil', 'Brasil, Brasilian');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302728, 'BS', 'Bahamas', NULL, 'https://en.wikipedia.org/wiki/Bahamas', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302625, 'BT', 'Bhutan', 'AS', 'https://en.wikipedia.org/wiki/Bhutan', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302560, 'BW', 'Botswana', 'AF', 'https://en.wikipedia.org/wiki/Botswana', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302678, 'BY', 'Belarus', 'EU', 'https://en.wikipedia.org/wiki/Belarus', 'Belarussian, Беларусь');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302729, 'BZ', 'Belize', NULL, 'https://en.wikipedia.org/wiki/Belize', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302730, 'CA', 'Canada', NULL, 'https://en.wikipedia.org/wiki/Canada', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302626, 'CC', 'Cocos (Keeling) Islands', 'AS', 'https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302561, 'CD', 'Congo (Kinshasa)', 'AF', 'https://en.wikipedia.org/wiki/Congo_(Kinshasa)', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302562, 'CF', 'Central African Republic', 'AF', 'https://en.wikipedia.org/wiki/Central_African_Republic', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302563, 'CG', 'Congo (Brazzaville)', 'AF', 'https://en.wikipedia.org/wiki/Congo_(Brazzaville)', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302679, 'CH', 'Switzerland', 'EU', 'https://en.wikipedia.org/wiki/Switzerland', 'Aéroports de la Suisse,Flughäfen der Schweiz');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302564, 'CI', 'Côte d'Ivoire', 'AF', 'https://en.wikipedia.org/wiki/Côte_d'Ivoire', 'Ivory Coast');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302765, 'CK', 'Cook Islands', 'OC', 'https://en.wikipedia.org/wiki/Cook_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302792, 'CL', 'Chile', 'SA', 'https://en.wikipedia.org/wiki/Chile', 'Aeropuertos de Chile');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302565, 'CM', 'Cameroon', 'AF', 'https://en.wikipedia.org/wiki/Cameroon', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302627, 'CN', 'China', 'AS', 'https://en.wikipedia.org/wiki/China', '中国的机场');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302793, 'CO', 'Colombia', 'SA', 'https://en.wikipedia.org/wiki/Colombia', 'Aeropuertos de Colombia');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302731, 'CR', 'Costa Rica', NULL, 'https://en.wikipedia.org/wiki/Costa_Rica', 'Aeropuertos de Costa Rica');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302732, 'CU', 'Cuba', NULL, 'https://en.wikipedia.org/wiki/Cuba', 'Aeropuertos de Cuba');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302566, 'CV', 'Cape Verde', 'AF', 'https://en.wikipedia.org/wiki/Cape_Verde', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302762, 'CW', 'Curaçao', NULL, 'https://en.wikipedia.org/wiki/Cura%C3%A7ao', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302628, 'CX', 'Christmas Island', 'AS', 'https://en.wikipedia.org/wiki/Christmas_Island', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302629, 'CY', 'Cyprus', 'AS', 'https://en.wikipedia.org/wiki/Cyprus', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302680, 'CZ', 'Czech Republic', 'EU', 'https://en.wikipedia.org/wiki/Czech_Republic', 'Letiště České republiky, Czechia');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302681, 'DE', 'Germany', 'EU', 'https://en.wikipedia.org/wiki/Germany', 'Flughäfen in Deutschland');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302567, 'DJ', 'Djibouti', 'AF', 'https://en.wikipedia.org/wiki/Djibouti', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302682, 'DK', 'Denmark', 'EU', 'https://en.wikipedia.org/wiki/Denmark', 'Lufthavnene i Danmark');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302733, 'DM', 'Dominica', NULL, 'https://en.wikipedia.org/wiki/Dominica', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302734, 'DO', 'Dominican Republic', NULL, 'https://en.wikipedia.org/wiki/Dominican_Republic', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302568, 'DZ', 'Algeria', 'AF', 'https://en.wikipedia.org/wiki/Algeria', 'مطارات الجزائر');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302794, 'EC', 'Ecuador', 'SA', 'https://en.wikipedia.org/wiki/Ecuador', 'Aeropuertos de Ecuador');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302683, 'EE', 'Estonia', 'EU', 'https://en.wikipedia.org/wiki/Estonia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302569, 'EG', 'Egypt', 'AF', 'https://en.wikipedia.org/wiki/Egypt', 'مطارات مصر');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302570, 'EH', 'Western Sahara', 'AF', 'https://en.wikipedia.org/wiki/Western_Sahara', 'Sahrawian, مطارات الصحراء الغربية');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302571, 'ER', 'Eritrea', 'AF', 'https://en.wikipedia.org/wiki/Eritrea', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302684, 'ES', 'Spain', 'EU', 'https://en.wikipedia.org/wiki/Spain', 'Aeropuertos de España');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302572, 'ET', 'Ethiopia', 'AF', 'https://en.wikipedia.org/wiki/Ethiopia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302685, 'FI', 'Finland', 'EU', 'https://en.wikipedia.org/wiki/Finland', 'Lentokentät, Suomen');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302766, 'FJ', 'Fiji', 'OC', 'https://en.wikipedia.org/wiki/Fiji', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302795, 'FK', 'Falkland Islands', 'SA', 'https://en.wikipedia.org/wiki/Falkland_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302767, 'FM', 'Micronesia', 'OC', 'https://en.wikipedia.org/wiki/Federated_States_of_Micronesia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302686, 'FO', 'Faroe Islands', 'EU', 'https://en.wikipedia.org/wiki/Faroe_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302687, 'FR', 'France', 'EU', 'https://en.wikipedia.org/wiki/France', 'Aéroports de France');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302573, 'GA', 'Gabon', 'AF', 'https://en.wikipedia.org/wiki/Gabon', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302688, 'GB', 'United Kingdom', 'EU', 'https://en.wikipedia.org/wiki/United_Kingdom', 'Great Britain');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302735, 'GD', 'Grenada', NULL, 'https://en.wikipedia.org/wiki/Grenada', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302630, 'GE', 'Georgia', 'AS', 'https://en.wikipedia.org/wiki/Georgia_(country)', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302796, 'GF', 'French Guiana', 'SA', 'https://en.wikipedia.org/wiki/French_Guiana', 'French Guyana');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302689, 'GG', 'Guernsey', 'EU', 'https://en.wikipedia.org/wiki/Guernsey', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302574, 'GH', 'Ghana', 'AF', 'https://en.wikipedia.org/wiki/Ghana', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302690, 'GI', 'Gibraltar', 'EU', 'https://en.wikipedia.org/wiki/Gibraltar', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302736, 'GL', 'Greenland', NULL, 'https://en.wikipedia.org/wiki/Greenland', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302575, 'GM', 'Gambia', 'AF', 'https://en.wikipedia.org/wiki/Gambia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302576, 'GN', 'Guinea', 'AF', 'https://en.wikipedia.org/wiki/Guinea', 'Aéroports de la Guinée');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302737, 'GP', 'Guadeloupe', NULL, 'https://en.wikipedia.org/wiki/Guadeloupe', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302577, 'GQ', 'Equatorial Guinea', 'AF', 'https://en.wikipedia.org/wiki/Equatorial_Guinea', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302691, 'GR', 'Greece', 'EU', 'https://en.wikipedia.org/wiki/Greece', 'αεροδρόμια στην Ελλάδα');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302616, 'GS', 'South Georgia and the South Sandwich Islands', 'AN', 'https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302738, 'GT', 'Guatemala', NULL, 'https://en.wikipedia.org/wiki/Guatemala', 'Aeropuertos de Guatemala');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302768, 'GU', 'Guam', 'OC', 'https://en.wikipedia.org/wiki/Guam', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302578, 'GW', 'Guinea-Bissau', 'AF', 'https://en.wikipedia.org/wiki/Guinea-Bissau', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302797, 'GY', 'Guyana', 'SA', 'https://en.wikipedia.org/wiki/Guyana', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302631, 'HK', 'Hong Kong', 'AS', 'https://en.wikipedia.org/wiki/Hong_Kong', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (350209, 'HM', 'Heard and McDonald Islands', 'OC', 'https://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302739, 'HN', 'Honduras', NULL, 'https://en.wikipedia.org/wiki/Honduras', 'Aeropuertos de Honduras');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302692, 'HR', 'Croatia', 'EU', 'https://en.wikipedia.org/wiki/Croatia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302740, 'HT', 'Haiti', NULL, 'https://en.wikipedia.org/wiki/Haiti', 'Aéroports de Haïti');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302693, 'HU', 'Hungary', 'EU', 'https://en.wikipedia.org/wiki/Hungary', 'Repülőterek Magyarország');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302632, 'ID', 'Indonesia', 'AS', 'https://en.wikipedia.org/wiki/Indonesia', 'Bandara di Indonesia');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302694, 'IE', 'Ireland', 'EU', 'https://en.wikipedia.org/wiki/Ireland', 'Eire');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302633, 'IL', 'Israel', 'AS', 'https://en.wikipedia.org/wiki/Israel', 'שדות התעופה של ישראל');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302695, 'IM', 'Isle of Man', 'EU', 'https://en.wikipedia.org/wiki/Isle_of_Man', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302634, 'IN', 'India', 'AS', 'https://en.wikipedia.org/wiki/India', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302635, 'IO', 'British Indian Ocean Territory', 'AS', 'https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302636, 'IQ', 'Iraq', 'AS', 'https://en.wikipedia.org/wiki/Iraq', 'مطارات العراق');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302637, 'IR', 'Iran', 'AS', 'https://en.wikipedia.org/wiki/Iran', 'فرودگاه های ایران');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302696, 'IS', 'Iceland', 'EU', 'https://en.wikipedia.org/wiki/Iceland', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302697, 'IT', 'Italy', 'EU', 'https://en.wikipedia.org/wiki/Italy', 'Aeroporti d'Italia');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302698, 'JE', 'Jersey', 'EU', 'https://en.wikipedia.org/wiki/Jersey', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302741, 'JM', 'Jamaica', NULL, 'https://en.wikipedia.org/wiki/Jamaica', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302638, 'JO', 'Jordan', 'AS', 'https://en.wikipedia.org/wiki/Jordan', 'مطارات في الأردن');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302639, 'JP', 'Japan', 'AS', 'https://en.wikipedia.org/wiki/Japan', 'Nippon, 日本の空港');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302579, 'KE', 'Kenya', 'AF', 'https://en.wikipedia.org/wiki/Kenya', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302640, 'KG', 'Kyrgyzstan', 'AS', 'https://en.wikipedia.org/wiki/Kyrgyzstan', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302641, 'KH', 'Cambodia', 'AS', 'https://en.wikipedia.org/wiki/Cambodia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302769, 'KI', 'Kiribati', 'OC', 'https://en.wikipedia.org/wiki/Kiribati', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302580, 'KM', 'Comoros', 'AF', 'https://en.wikipedia.org/wiki/Comoros', 'جزر القمر');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302742, 'KN', 'Saint Kitts and Nevis', NULL, 'https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302642, 'KP', 'North Korea', 'AS', 'https://en.wikipedia.org/wiki/North_Korea', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302643, 'KR', 'South Korea', 'AS', 'https://en.wikipedia.org/wiki/South_Korea', '한국의 공항');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302644, 'KW', 'Kuwait', 'AS', 'https://en.wikipedia.org/wiki/Kuwait', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302743, 'KY', 'Cayman Islands', NULL, 'https://en.wikipedia.org/wiki/Cayman_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302645, 'KZ', 'Kazakhstan', 'AS', 'https://en.wikipedia.org/wiki/Kazakhstan', 'Kazakh');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302646, 'LA', 'Laos', 'AS', 'https://en.wikipedia.org/wiki/Laos', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302647, 'LB', 'Lebanon', 'AS', 'https://en.wikipedia.org/wiki/Lebanon', 'المطارات في لبنان');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302744, 'LC', 'Saint Lucia', NULL, 'https://en.wikipedia.org/wiki/Saint_Lucia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302699, 'LI', 'Liechtenstein', 'EU', 'https://en.wikipedia.org/wiki/Liechtenstein', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302648, 'LK', 'Sri Lanka', 'AS', 'https://en.wikipedia.org/wiki/Sri_Lanka', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302581, 'LR', 'Liberia', 'AF', 'https://en.wikipedia.org/wiki/Liberia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302582, 'LS', 'Lesotho', 'AF', 'https://en.wikipedia.org/wiki/Lesotho', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302700, 'LT', 'Lithuania', 'EU', 'https://en.wikipedia.org/wiki/Lithuania', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302701, 'LU', 'Luxembourg', 'EU', 'https://en.wikipedia.org/wiki/Luxembourg', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302702, 'LV', 'Latvia', 'EU', 'https://en.wikipedia.org/wiki/Latvia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302583, 'LY', 'Libya', 'AF', 'https://en.wikipedia.org/wiki/Libya', 'مطارات في ليبيا');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302584, 'MA', 'Morocco', 'AF', 'https://en.wikipedia.org/wiki/Morocco', 'مطارات المغرب');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302703, 'MC', 'Monaco', 'EU', 'https://en.wikipedia.org/wiki/Monaco', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302704, 'MD', 'Moldova', 'EU', 'https://en.wikipedia.org/wiki/Moldova', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302705, 'ME', 'Montenegro', 'EU', 'https://en.wikipedia.org/wiki/Montenegro', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302759, 'MF', 'Saint Martin', NULL, 'https://en.wikipedia.org/wiki/Saint_Martin_(France)', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302585, 'MG', 'Madagascar', 'AF', 'https://en.wikipedia.org/wiki/Madagascar', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302770, 'MH', 'Marshall Islands', 'OC', 'https://en.wikipedia.org/wiki/Marshall_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302706, 'MK', 'North Macedonia', 'EU', 'https://en.wikipedia.org/wiki/Macedonia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302586, 'ML', 'Mali', 'AF', 'https://en.wikipedia.org/wiki/Mali', 'Aéroports du Mali');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302649, 'MM', 'Burma', 'AS', 'https://en.wikipedia.org/wiki/Burma', 'Myanmar');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302650, 'MN', 'Mongolia', 'AS', 'https://en.wikipedia.org/wiki/Mongolia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302651, 'MO', 'Macau', 'AS', 'https://en.wikipedia.org/wiki/Macau', 'Macao');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302771, 'MP', 'Northern Mariana Islands', 'OC', 'https://en.wikipedia.org/wiki/Northern_Mariana_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302745, 'MQ', 'Martinique', NULL, 'https://en.wikipedia.org/wiki/Martinique', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302587, 'MR', 'Mauritania', 'AF', 'https://en.wikipedia.org/wiki/Mauritania', 'مطارات موريتانيا');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302746, 'MS', 'Montserrat', NULL, 'https://en.wikipedia.org/wiki/Montserrat', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302707, 'MT', 'Malta', 'EU', 'https://en.wikipedia.org/wiki/Malta', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302588, 'MU', 'Mauritius', 'AF', 'https://en.wikipedia.org/wiki/Mauritius', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302652, 'MV', 'Maldives', 'AS', 'https://en.wikipedia.org/wiki/Maldives', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302589, 'MW', 'Malawi', 'AF', 'https://en.wikipedia.org/wiki/Malawi', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302747, 'MX', 'Mexico', NULL, 'https://en.wikipedia.org/wiki/Mexico', 'Aeropuertos de México');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302653, 'MY', 'Malaysia', 'AS', 'https://en.wikipedia.org/wiki/Malaysia', 'Lapangan Terbang Malaysia');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302590, 'MZ', 'Mozambique', 'AF', 'https://en.wikipedia.org/wiki/Mozambique', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302591, NULL, 'Namibia', 'AF', 'https://en.wikipedia.org/wiki/Namibia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302772, 'NC', 'New Caledonia', 'OC', 'https://en.wikipedia.org/wiki/New_Caledonia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302592, 'NE', 'Niger', 'AF', 'https://en.wikipedia.org/wiki/Niger', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302773, 'NF', 'Norfolk Island', 'OC', 'https://en.wikipedia.org/wiki/Norfolk_Island', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302593, 'NG', 'Nigeria', 'AF', 'https://en.wikipedia.org/wiki/Nigeria', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302748, 'NI', 'Nicaragua', NULL, 'https://en.wikipedia.org/wiki/Nicaragua', 'Aeropuertos de Nicaragua');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302708, 'NL', 'Netherlands', 'EU', 'https://en.wikipedia.org/wiki/Netherlands', 'Holland,Luchthavens van Nederland');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302709, 'NO', 'Norway', 'EU', 'https://en.wikipedia.org/wiki/Norway', 'Flyplasser i Norge');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302654, 'NP', 'Nepal', 'AS', 'https://en.wikipedia.org/wiki/Nepal', 'नेपाल विमानस्थलको');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302774, 'NR', 'Nauru', 'OC', 'https://en.wikipedia.org/wiki/Nauru', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302775, 'NU', 'Niue', 'OC', 'https://en.wikipedia.org/wiki/Niue', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302776, 'NZ', 'New Zealand', 'OC', 'https://en.wikipedia.org/wiki/New_Zealand', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302655, 'OM', 'Oman', 'AS', 'https://en.wikipedia.org/wiki/Oman', 'مطارات عمان');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302749, 'PA', 'Panama', NULL, 'https://en.wikipedia.org/wiki/Panama', 'Aeropuertos de Panamá');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302798, 'PE', 'Perú', 'SA', 'https://en.wikipedia.org/wiki/Perú', 'Aeropuertos de Perú');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302777, 'PF', 'French Polynesia', 'OC', 'https://en.wikipedia.org/wiki/French_Polynesia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302778, 'PG', 'Papua New Guinea', 'OC', 'https://en.wikipedia.org/wiki/Papua_New_Guinea', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302656, 'PH', 'Philippines', 'AS', 'https://en.wikipedia.org/wiki/Philippines', 'Mga alternatibong byahe mula sa Pilipinas');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302657, 'PK', 'Pakistan', 'AS', 'https://en.wikipedia.org/wiki/Pakistan', 'پاکستان کے ہوائی اڈوں');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302710, 'PL', 'Poland', 'EU', 'https://en.wikipedia.org/wiki/Poland', 'Lotniska Polski');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302750, 'PM', 'Saint Pierre and Miquelon', NULL, 'https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302779, 'PN', 'Pitcairn', 'OC', 'https://en.wikipedia.org/wiki/Pitcairn', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302751, 'PR', 'Puerto Rico', NULL, 'https://en.wikipedia.org/wiki/Puerto_Rico', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302658, 'PS', 'Palestinian Territory', 'AS', 'https://en.wikipedia.org/wiki/Palestinian_Territory', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302711, 'PT', 'Portugal', 'EU', 'https://en.wikipedia.org/wiki/Portugal', 'Aeroportos do Brasil');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302780, 'PW', 'Palau', 'OC', 'https://en.wikipedia.org/wiki/Palau', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302799, 'PY', 'Paraguay', 'SA', 'https://en.wikipedia.org/wiki/Paraguay', 'Aeropuertos de Paraguay');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302659, 'QA', 'Qatar', 'AS', 'https://en.wikipedia.org/wiki/Qatar', 'مطارات قطر');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302594, 'RE', 'Réunion', 'AF', 'https://en.wikipedia.org/wiki/Réunion', 'Île Bourbon, La Réunion');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302712, 'RO', 'Romania', 'EU', 'https://en.wikipedia.org/wiki/Romania', 'Aeroporturi din România');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302713, 'RS', 'Serbia', 'EU', 'https://en.wikipedia.org/wiki/Serbia', 'Serb');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302714, 'RU', 'Russia', 'EU', 'https://en.wikipedia.org/wiki/Russia', 'Soviet, Sovietskaya, Sovetskaya, Аэропорты России');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302595, 'RW', 'Rwanda', 'AF', 'https://en.wikipedia.org/wiki/Rwanda', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302660, 'SA', 'Saudi Arabia', 'AS', 'https://en.wikipedia.org/wiki/Saudi_Arabia', 'مطارات المملكة العربية السعودية,المطارات لموسم الحج');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302781, 'SB', 'Solomon Islands', 'OC', 'https://en.wikipedia.org/wiki/Solomon_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302596, 'SC', 'Seychelles', 'AF', 'https://en.wikipedia.org/wiki/Seychelles', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302597, 'SD', 'Sudan', 'AF', 'https://en.wikipedia.org/wiki/Sudan', 'مطارات السودان');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302715, 'SE', 'Sweden', 'EU', 'https://en.wikipedia.org/wiki/Sweden', 'Flygplatserna, Sverige');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302661, 'SG', 'Singapore', 'AS', 'https://en.wikipedia.org/wiki/Singapore', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302598, 'SH', 'Saint Helena, Ascension and Tristan da Cunha', 'AF', 'https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302716, 'SI', 'Slovenia', 'EU', 'https://en.wikipedia.org/wiki/Slovenia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302717, 'SK', 'Slovakia', 'EU', 'https://en.wikipedia.org/wiki/Slovakia', 'letisko Slovenska');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302599, 'SL', 'Sierra Leone', 'AF', 'https://en.wikipedia.org/wiki/Sierra_Leone', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302718, 'SM', 'San Marino', 'EU', 'https://en.wikipedia.org/wiki/San_Marino', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302600, 'SN', 'Senegal', 'AF', 'https://en.wikipedia.org/wiki/Senegal', 'Aéroports du Sénégal');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302601, 'SO', 'Somalia', 'AF', 'https://en.wikipedia.org/wiki/Somalia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302800, 'SR', 'Suriname', 'SA', 'https://en.wikipedia.org/wiki/Suriname', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302614, 'SS', 'South Sudan', 'AF', 'https://en.wikipedia.org/wiki/South_Sudan', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302602, 'ST', 'São Tomé and Principe', 'AF', 'https://en.wikipedia.org/wiki/São_Tomé_and_Principe', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302752, 'SV', 'El Salvador', NULL, 'https://en.wikipedia.org/wiki/El_Salvador', 'Salvadorian, Salvadorean');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302761, 'SX', 'Sint Maarten', NULL, 'https://en.wikipedia.org/wiki/Sint_Maarten', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302662, 'SY', 'Syria', 'AS', 'https://en.wikipedia.org/wiki/Syria', 'مطارات سوريا');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302603, 'SZ', 'Eswatini', 'AF', 'https://en.wikipedia.org/wiki/Eswatini', 'Swaziland');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302753, 'TC', 'Turks and Caicos Islands', NULL, 'https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302604, 'TD', 'Chad', 'AF', 'https://en.wikipedia.org/wiki/Chad', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302617, 'TF', 'French Southern and Antarctic Lands', 'AF', 'https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302605, 'TG', 'Togo', 'AF', 'https://en.wikipedia.org/wiki/Togo', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302663, 'TH', 'Thailand', 'AS', 'https://en.wikipedia.org/wiki/Thailand', 'Siam, Siamese');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302664, 'TJ', 'Tajikistan', 'AS', 'https://en.wikipedia.org/wiki/Tajikistan', 'Tajik');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302782, 'TK', 'Tokelau', 'OC', 'https://en.wikipedia.org/wiki/Tokelau', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302665, 'TL', 'Timor-Leste', 'AS', 'https://en.wikipedia.org/wiki/Timor-Leste', 'East Timor');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302666, 'TM', 'Turkmenistan', 'AS', 'https://en.wikipedia.org/wiki/Turkmenistan', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302606, 'TN', 'Tunisia', 'AF', 'https://en.wikipedia.org/wiki/Tunisia', 'مطارات تونس');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302783, 'TO', 'Tonga', 'OC', 'https://en.wikipedia.org/wiki/Tonga', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302667, 'TR', 'Turkey', 'AS', 'https://en.wikipedia.org/wiki/Turkey', 'Türkiye havaalanları');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302754, 'TT', 'Trinidad and Tobago', NULL, 'https://en.wikipedia.org/wiki/Trinidad_and_Tobago', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302784, 'TV', 'Tuvalu', 'OC', 'https://en.wikipedia.org/wiki/Tuvalu', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302668, 'TW', 'Taiwan', 'AS', 'https://en.wikipedia.org/wiki/Taiwan', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302607, 'TZ', 'Tanzania', 'AF', 'https://en.wikipedia.org/wiki/Tanzania', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302719, 'UA', 'Ukraine', 'EU', 'https://en.wikipedia.org/wiki/Ukraine', 'Аеропорти України');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302608, 'UG', 'Uganda', 'AF', 'https://en.wikipedia.org/wiki/Uganda', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302785, 'UM', 'United States Minor Outlying Islands', 'OC', 'https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302755, 'US', 'United States', NULL, 'https://en.wikipedia.org/wiki/United_States', 'America');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302801, 'UY', 'Uruguay', 'SA', 'https://en.wikipedia.org/wiki/Uruguay', 'Aeropuertos de Uruguay');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302669, 'UZ', 'Uzbekistan', 'AS', 'https://en.wikipedia.org/wiki/Uzbekistan', 'Uzbek');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302721, 'VA', 'Vatican City', 'EU', 'https://en.wikipedia.org/wiki/Vatican_City', 'The Holy See');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302756, 'VC', 'Saint Vincent and the Grenadines', NULL, 'https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302802, 'VE', 'Venezuela', 'SA', 'https://en.wikipedia.org/wiki/Venezuela', 'Aeropuertos de Venezuela');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302757, 'VG', 'British Virgin Islands', NULL, 'https://en.wikipedia.org/wiki/British_Virgin_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302758, 'VI', 'U.S. Virgin Islands', NULL, 'https://en.wikipedia.org/wiki/U.S._Virgin_Islands', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302670, 'VN', 'Vietnam', 'AS', 'https://en.wikipedia.org/wiki/Vietnam', 'Các sân bay của Việt Nam');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302786, 'VU', 'Vanuatu', 'OC', 'https://en.wikipedia.org/wiki/Vanuatu', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302787, 'WF', 'Wallis and Futuna', 'OC', 'https://en.wikipedia.org/wiki/Wallis_and_Futuna', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302788, 'WS', 'Samoa', 'OC', 'https://en.wikipedia.org/wiki/Samoa', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302720, 'XK', 'Kosovo', 'EU', 'https://en.wikipedia.org/wiki/Kosovo', 'Kosova');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302671, 'YE', 'Yemen', 'AS', 'https://en.wikipedia.org/wiki/Yemen', 'مطارات اليمن');
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302609, 'YT', 'Mayotte', 'AF', 'https://en.wikipedia.org/wiki/Mayotte', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302610, 'ZA', 'South Africa', 'AF', 'https://en.wikipedia.org/wiki/South_Africa', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302611, 'ZM', 'Zambia', 'AF', 'https://en.wikipedia.org/wiki/Zambia', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302612, 'ZW', 'Zimbabwe', 'AF', 'https://en.wikipedia.org/wiki/Zimbabwe', NULL);
INSERT INTO countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302613, 'ZZ', 'Unknown or unassigned country', 'AF', 'https://en.wikipedia.org/wiki/Unknown_or_unassigned_country', NULL);
